% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef Gradient < handle
  properties
    % Grad header
    head
    % gradient data
    data
  end

  methods
    function self = Gradient(kwargs)
      arguments
        kwargs.head = mrd.GradientHeader();
        kwargs.data = single.empty();
      end
      self.head = kwargs.head;
      self.data = kwargs.data;
    end

    function res = samples(self)
      res = size(self.data, ndims(self.data)-(0));
      return
    end

    function res = starttime(self)
      % timestamps in ns
      res = self.head.gradient_time_stamp_ns;
      return
    end

    function res = endtime(self)
      res = self.head.gradient_time_stamp_ns + self.samples() .* uint64(self.head.gradient_sample_time_ns);
      return
    end


    function res = eq(self, other)
      res = ...
        isa(other, "mrd.Gradient") && ...
        isequal({self.head}, {other.head}) && ...
        isequal({self.data}, {other.data});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.Gradient();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
