% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef GradientAxis < uint64
  methods (Static)
    function v = Z
      v = mrd.GradientAxis(1);
    end
    function v = Y
      v = mrd.GradientAxis(2);
    end
    function v = X
      v = mrd.GradientAxis(3);
    end

    function z = zeros(varargin)
      elem = mrd.GradientAxis(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
