% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef GradientHeader < handle
  properties
    gradient_time_stamp_ns
    gradient_sample_time_ns
    pulse_calibration
  end

  methods
    function self = GradientHeader(kwargs)
      arguments
        kwargs.gradient_time_stamp_ns = uint64(0);
        kwargs.gradient_sample_time_ns = uint32(0);
        kwargs.pulse_calibration = yardl.None;
      end
      self.gradient_time_stamp_ns = kwargs.gradient_time_stamp_ns;
      self.gradient_sample_time_ns = kwargs.gradient_sample_time_ns;
      self.pulse_calibration = kwargs.pulse_calibration;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.GradientHeader") && ...
        isequal({self.gradient_time_stamp_ns}, {other.gradient_time_stamp_ns}) && ...
        isequal({self.gradient_sample_time_ns}, {other.gradient_sample_time_ns}) && ...
        isequal({self.pulse_calibration}, {other.pulse_calibration});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.GradientHeader();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
