% This file was generated by the "yardl" tool. DO NOT EDIT.

<<<<<<< HEAD
<<<<<<<< HEAD:matlab/toolbox/+mrd/ImageMeta.m
classdef ImageMeta < yardl.Map
========
function c = ImageUint32(varargin)
  c = mrd.Image(varargin{:});
>>>>>>>> 34594f0a430fc035361e38f998636583f38fc1fe:matlab/toolbox/+mrd/ImageUint32.m
=======
function m = ImageMeta(varargin)
  m = dictionary(varargin{:});
>>>>>>> 34594f0a430fc035361e38f998636583f38fc1fe
end
