% This file was generated by the "yardl" tool. DO NOT EDIT.

<<<<<<< HEAD
classdef ImageInt32 < mrd.Image
=======
function c = ImageInt32(varargin)
  c = mrd.Image(varargin{:});
>>>>>>> 34594f0a430fc035361e38f998636583f38fc1fe
end
