% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ImageQuantitativeType < uint64
  methods (Static)
    function v = QUANT_T1
      v = mrd.ImageQuantitativeType(1);
    end
    function v = QUANT_T2STAR
      v = mrd.ImageQuantitativeType(2);
    end
    function v = QUANT_ADC
      v = mrd.ImageQuantitativeType(3);
    end
    function v = QUANT_SPIN_DENSITY
      v = mrd.ImageQuantitativeType(4);
    end
    function v = QUANT_B1_MAP
      v = mrd.ImageQuantitativeType(5);
    end
    function v = QUANT_SENSITIVITY_MAP
      v = mrd.ImageQuantitativeType(6);
    end

    function z = zeros(varargin)
      elem = mrd.ImageQuantitativeType(0);
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
