% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef ReconData < handle
  properties
    buffers
  end

  methods
    function self = ReconData(kwargs)
      arguments
        kwargs.buffers = mrd.ReconAssembly.empty();
      end
      self.buffers = kwargs.buffers;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.ReconData") && ...
<<<<<<< HEAD
        isequal({self.buffers}, {other.buffers});
=======
        isequal(self.buffers, other.buffers);
>>>>>>> 34594f0a430fc035361e38f998636583f38fc1fe
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.ReconData();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
