% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TrapezoidalGradient < handle
  % A trapezoidal gradient event
  properties
    % ID of the gradient event. Must be unique among all arbitrary and trapezoidal gradient events.
    id
    % Peak amplitude in Hz/m
    amp
    % Rise time of the trapezoid in microseconds
    % rise: uint64
    rise_ns
    % Flat-top time of the trapezoid in microseconds
    % flat: uint64
    flat_ns
    % Fall time of the trapezoid in microseconds
    % fall: uint64
    fall_ns
    % Delay before starting the gradient, specified in microseconds
    % delay: uint64
    delay_ns
  end

  methods
    function self = TrapezoidalGradient(kwargs)
      arguments
        kwargs.id = int32(0);
        kwargs.amp = double(0);
        kwargs.rise_ns = uint64(0);
        kwargs.flat_ns = uint64(0);
        kwargs.fall_ns = uint64(0);
        kwargs.delay_ns = uint64(0);
      end
      self.id = kwargs.id;
      self.amp = kwargs.amp;
      self.rise_ns = kwargs.rise_ns;
      self.flat_ns = kwargs.flat_ns;
      self.fall_ns = kwargs.fall_ns;
      self.delay_ns = kwargs.delay_ns;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "mrd.TrapezoidalGradient") && ...
        isequal({self.id}, {other.id}) && ...
        isequal({self.amp}, {other.amp}) && ...
        isequal({self.rise_ns}, {other.rise_ns}) && ...
        isequal({self.flat_ns}, {other.flat_ns}) && ...
        isequal({self.fall_ns}, {other.fall_ns}) && ...
        isequal({self.delay_ns}, {other.delay_ns});
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end

    function res = isequal(self, other)
      res = all(eq(self, other));
    end
  end

  methods (Static)
    function z = zeros(varargin)
      elem = mrd.TrapezoidalGradient();
      if nargin == 0
        z = elem;
        return;
      end
      sz = [varargin{:}];
      if isscalar(sz)
        sz = [sz, sz];
      end
      z = reshape(repelem(elem, prod(sz)), sz);
    end
  end
end
