% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef GradHeaderSerializer < yardl.binary.RecordSerializer
  methods
    function self = GradHeaderSerializer()
      field_serializers{1} = yardl.binary.Uint64Serializer;
      field_serializers{2} = yardl.binary.Uint32Serializer;
      field_serializers{3} = yardl.binary.OptionalSerializer(yardl.binary.VectorSerializer(yardl.binary.Float32Serializer));
      self@yardl.binary.RecordSerializer('mrd.GradHeader', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.GradHeader
      end
      self.write_(outstream, value.gradient_time_stamp_ns, value.gradient_sample_time_ns, value.pulse_calibration);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.GradHeader(gradient_time_stamp_ns=fields{1}, gradient_sample_time_ns=fields{2}, pulse_calibration=fields{3});
    end
  end
end
