% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef MrdNoiseCovarianceReader < yardl.binary.BinaryProtocolReader & mrd.MrdNoiseCovarianceReaderBase
  % Binary reader for the MrdNoiseCovariance protocol
<<<<<<< HEAD
=======
  % Protocol for serializing a noise covariance matrix
>>>>>>> 34594f0a430fc035361e38f998636583f38fc1fe
  properties (Access=protected)
    noise_covariance_serializer
  end

  methods
    function self = MrdNoiseCovarianceReader(filename)
      self@mrd.MrdNoiseCovarianceReaderBase();
      self@yardl.binary.BinaryProtocolReader(filename, mrd.MrdNoiseCovarianceReaderBase.schema);
      self.noise_covariance_serializer = mrd.binary.NoiseCovarianceSerializer();
    end
  end

  methods (Access=protected)
    function value = read_noise_covariance_(self)
      value = self.noise_covariance_serializer.read(self.stream_);
    end
  end
end
