% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef MrdNoiseCovarianceWriter < yardl.binary.BinaryProtocolWriter & mrd.MrdNoiseCovarianceWriterBase
  % Binary writer for the MrdNoiseCovariance protocol
<<<<<<< HEAD
=======
  % Protocol for serializing a noise covariance matrix
>>>>>>> 34594f0a430fc035361e38f998636583f38fc1fe
  properties (Access=protected)
    noise_covariance_serializer
  end

  methods
    function self = MrdNoiseCovarianceWriter(filename)
      self@mrd.MrdNoiseCovarianceWriterBase();
      self@yardl.binary.BinaryProtocolWriter(filename, mrd.MrdNoiseCovarianceWriterBase.schema);
      self.noise_covariance_serializer = mrd.binary.NoiseCovarianceSerializer();
    end
  end

  methods (Access=protected)
    function write_noise_covariance_(self, value)
      self.noise_covariance_serializer.write(self.stream_, value);
    end
  end
end
