% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef TrapezoidalGradientSerializer < yardl.binary.RecordSerializer
  methods
    function self = TrapezoidalGradientSerializer()
      field_serializers{1} = yardl.binary.Int32Serializer;
      field_serializers{2} = yardl.binary.Float64Serializer;
      field_serializers{3} = yardl.binary.Uint64Serializer;
      field_serializers{4} = yardl.binary.Uint64Serializer;
      field_serializers{5} = yardl.binary.Uint64Serializer;
      field_serializers{6} = yardl.binary.Uint64Serializer;
      self@yardl.binary.RecordSerializer('mrd.TrapezoidalGradient', field_serializers);
    end

    function write(self, outstream, value)
      arguments
        self
        outstream (1,1) yardl.binary.CodedOutputStream
        value (1,1) mrd.TrapezoidalGradient
      end
      self.write_(outstream, value.id, value.amp, value.rise_ns, value.flat_ns, value.fall_ns, value.delay_ns);
    end

    function value = read(self, instream)
      fields = self.read_(instream);
      value = mrd.TrapezoidalGradient(id=fields{1}, amp=fields{2}, rise_ns=fields{3}, flat_ns=fields{4}, fall_ns=fields{5}, delay_ns=fields{6});
    end
  end
end
